return {
	"nvim-treesitter/nvim-treesitter",
	build = ":TSUpdate",
	opts = {
  ensure_installed = {
    "bash",
    "c",
    "cpp",
    "css",
    "diff",
    "dockerfile",
    "gdscript",
    "gdshader",
    "gitignore",
    "godot_resource",
    "graphql",
    "haskell",
    "html",
    "javascript",
    "jsdoc",
    "json",
    "jsonc",
    "lua",
    "luadoc",
    "luap",
    "markdown",
    "markdown_inline",
    "prisma",
    "python",
    "query",
    "regex",
    "svelte",
    "toml",
    "tsx",
    "typescript",
    "vim",
    "vimdoc",
    "yaml",
  },
		auto_install = true,
		highlight = { enable = true },
		indent = { enable = true },
    autotag = {enable = true},
	},
	config = function(_, opts)
		require("nvim-treesitter.config").setup(opts)
	end,
}

